name: Build, Push and Deploy Docker Image with Rollback

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

      - name: Push Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/flask-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-app:stable
             docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:stable

      - name: Deploy Application (Mock)
        run: |
          echo "Deploying application..."
          # Simulating a failure here for test
          exit 1

      - name: Rollback if Deployment Fails
        if: failure()  # This step will only run if the previous one fails
        run: |
          echo "Deployment failed. Rolling back to previous stable image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/flask-app@sha256:2279513afe1ab1515a8658dcc93a9d08599b680d
          echo "Rollback complete!"
